<?php
// config/inovasi.php
return [
    'asta_cipta' => [
        'asta1' => 'Memperkokoh ideologi Pancasila, demokrasi, dan hak asasi manusia (HAM).',
        'asta2' => 'Memantapkan sistem pertahanan keamanan negara dan mendorong kemandirian bangsa melalui swasembada pangan, energi, air, ekonomi kreatif, ekonomi hijau, dan ekonomi biru.',
        'asta3' => 'Meningkatkan lapangan kerja yang berkualitas, mendorong kewirausahaan, mengembangkan industri kreatif, dan melanjutkan pengembangan infrastruktur.',
        'asta4' => 'Memperkuat pembangunan SDM, sains, teknologi, pendidikan, kesehatan, prestasi olahraga, kesetaraan gender, serta penguatan peran perempuan, pemuda, dan penyandang disabilitas.',
        'asta5' => 'Melanjutkan hilirisasi dan industrialisasi untuk meningkatkan nilai tambah di dalam negeri.',
        'asta6' => 'Membangun dari desa dan dari bawah untuk pemerataan ekonomi dan pemberantasan kemiskinan.',
        'asta7' => 'Memperkuat reformasi politik, hukum, dan birokrasi, serta pencegahan/ pemberantasan korupsi dan narkoba.',
        'asta8' => 'Menyelaraskan kehidupan harmonis dengan lingkungan, alam, dan budaya; peningkatan toleransi; menuju masyarakat adil dan makmur.',
    ],

    'program_prioritas' => [
        'progwalkot_1' => 'Makassar SuperApps (layanan publik terpadu).',
        'progwalkot_2' => 'Makassar Creative Hub (pengembangan keterampilan & inovasi).',
        'progwalkot_3' => 'Penyediaan Air Bersih (peluncuran bulan depan).',
        'progwalkot_4' => 'Seragam Gratis (SD/SMP keluarga kurang mampu).',
        'progwalkot_5' => 'Iuran Sampah Gratis (kebersihan).',
        'progwalkot_6' => 'Makassar Social Assistant (bansos terpadu).',
        'progwalkot_7' => 'Pembangunan Stadion Internasional.',
    ],

    // ↓ gunakan kode pendek yang konsisten di DB
    'urusan_pemerintah' => [
        'pendidikan' => 'Pendidikan',
        'kesehatan' => 'Kesehatan',
        'pu_pr' => 'Pekerjaan Umum dan Penataan Ruang',
        'perumahan' => 'Perumahan Rakyat dan Kawasan Permukiman',
        'trantib_linmas' => 'Ketentraman, Ketertiban Umum, dan Pelindungan Masyarakat',
        'sosial' => 'Sosial',
        'tenaga_kerja' => 'Tenaga Kerja',
        'pppa' => 'Pemberdayaan Perempuan dan Perlindungan Anak',
        'pangan' => 'Pangan',
        'pertanahan' => 'Pertanahan',
        'lingkungan' => 'Lingkungan Hidup',
        'adm_dukcapil' => 'Administrasi Kependudukan dan Pecatatan Sipil',
        'pmd' => 'Pemberdayaan Masyarakat dan Desa',
        'ppkb' => 'Pengendalian Penduduk dan Keluarga Berencana',
        'perhubungan' => 'Perhubungan',
        'kominfo' => 'Komunikasi dan Informatika',
        'kUMKM' => 'Koperasi, Usaha Kecil, dan Menengah',
        'penanaman_modal' => 'Penanaman Modal',
        'kepemudaan_olahraga' => 'Kepemudaan dan Olahraga',
        'statistik' => 'Statistik',
        'persandian' => 'Persandian',
        'kebudayaan' => 'Kebudayaan',
        'perpustakaan' => 'Perpustakaan',
        'kearsipan' => 'Kearsipan',
        'kelautan_perikanan' => 'Kelautan dan Perikanan',
        'pariwisata' => 'Pariwisata',
        'pertanian' => 'Pertanian',
        'kehutanan' => 'Kehutanan',
        'energi_sdm' => 'Energi dan Sumber Daya Mineral',
        'perdagangan' => 'Perdagangan',
        'perindustrian' => 'Perindustrian',
        'transmigrasi' => 'Transmigrasi',
        'perencanaan' => 'Perencanaan',
        'keuangan' => 'Keuangan',
        'kepegawaian' => 'Kepegawalan',
        'diklat' => 'Pendidikan dan Pelatihan',
        'litbang' => 'Penelitian dan Pengembangan',
        'fungsi_lain' => 'Fungsi lain sesuai ketentuan peraturan perundang-undangan',
    ],
];
